---
# handlers file for roles/kubernetesCore main
- name: restart kubelet
  become: true
  ansible.builtin.systemd:
    masked: no
    enabled: yes
    name: kubelet
    state: restarted
    daemon_reload: yes
    daemon_reexec: yes
