---
# tasks file for roles/haproxy main
- name: Validate Python Interpeter
  ansible.builtin.include_role:
    name: kubernetesCore
    tasks_from: interpreterValidation
  vars:
    pythonInterpreter: "python"

- name: Uninstall old version
  ansible.builtin.include_tasks: uninstall.yml

- name: Install haproxy
  ansible.builtin.include_tasks: install.yml

- name: Get CA certificates from Vault for HaProxy
  ansible.builtin.include_role:
    name: vault

- name: Copy CAs to remote node(s)
  ansible.builtin.include_tasks: haproxyCA.yml

- name: Copy config file(s)
  ansible.builtin.include_tasks: config.yml
