---
# tasks file for roles/harvester configuration
- name: Prepare Harvester conf file(s)
  ansible.builtin.template:
    dest: "{{ role_path }}/files/{{ item.key }}.yaml"
    src: "configuration.j2"
    mode: '0644'
  loop: "{{ lookup('ansible.builtin.dict', configuration.hosts) }}"
