---
# tasks file for roles/harvester configuration
- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    dest: "{{ role_path }}/files/{{ item }}"
    src: "configuration.j2"
    backup: true
    mode: '0644'
  with_items: "{{ configuration.nodes }}"

