---
# tasks file for roles/createUser addUser 
- name: Set dictionary key var for docker
  ansible.builtin.set_fact:
    key: 'docker'
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '7'

- name: Set dictionary key var for podman
  ansible.builtin.set_fact:
    key: 'podman'
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '8'

- name: Increase user namespace
  become: true
  ansible.builtin.shell:
    cmd: "{{ item }}"
  loop: "{{ podmanNamespace }}"
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '8'

- name: Remove /etc/*.lock files if exist
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop: "{{ systemFilesLinuxManagement }}"

- name: Create user and populate ssh keys
  become: true
  ansible.builtin.user:
    uid: "{{ item.uid }}"
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    append: true
    update_password: always
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    expires: -1
  loop: "{{ userParameters[key] }}"

- name: Change password expiry date (never)
  become: true
  ansible.builtin.shell:
    cmd: "chage -M -1 {{ item.name }}"
  loop: "{{ userParameters.podman }}"
