---
# tasks file for roles/kubernetesCore ingressHaProxyHeaders
- name: Ingress headers deployment with '{{ ingressOption }}' in '{{ ingress.metadata.namespace }}'
  community.kubernetes.k8s:
    state: "{{ ingressState | default('present') }}"
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ ingress.metadata.name }}"
        namespace: "{{ ingress.metadata.namespace }}"
        annotations:
          haproxy.org/cors-allow-headers: "*"
      spec: "{{ spec | from_yaml }}"
  vars:
    spec: |
      tls:
      - hosts:
          - "{{ ingress.spec.tls.hosts }}"
        secretName: "secret-{{ kubeadm.cluster.namespace }}"
      rules:
      - host: "{{ ingress.spec.rules.host }}"
        http:
          paths:
          - path: "{{ ingress.spec.rules.http.paths.path }}"
            pathType: "{{ ingress.spec.rules.http.paths.pathType }}"
            backend:
              service:
                name: "{{ ingress.spec.rules.http.paths.backend.service.name }}"
                port:
                  number: {{ ingress.spec.rules.http.paths.backend.service.port.number }}
  connection: local
  delegate_to: localhost
