---
# tasks file for roles/kubernetesCore interpreterValidation
- name: Validate we run with the correct Ansible interpreter
  assert:
    that:
      - ansible_python.executable == "/usr/bin/{{ pythonInterpreter }}"
    fail_msg: "'Ansible' interpreter must be {{ pythonInterpreter }} check ansible.cfg or inventory."
  connection: local
  delegate_to: localhost
  run_once: true
