---
# tasks file for kubernetesCore kubeconfig
- name: Setup kubeconfig dir for '{{ user }}' user
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    recurse: yes
  loop:
    - "{{ user_home_dir.stdout }}/.kube"
    - "/etc/kubernetes/manifests"

- name: Copy admin.conf to '{{ user }}' kube
  become: true
  ansible.builtin.command: "cp -i /etc/kubernetes/{{ configFile }} {{ user_home_dir.stdout }}/.kube/config"

- name: Setup kubeconfig for '{{ user }}' user
  become: true
  ansible.builtin.file:
    path: "{{ user_home_dir.stdout }}/.kube/config"
    owner: "{{ user }}"
    group: "{{ user }}"
