---
# tasks file for roles/kubernetesCore kubeconfigAdmin
- name: Create kubeconfig dir for 'admin' user
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    recurse: yes
  connection: local
  delegate_to: localhost

- name: Get ~/.kube/config for admin locally
  become: true
  ansible.posix.synchronize:
    mode: pull
    src: "/etc/kubernetes/{{ configFile }}"
    dest: ~/.kube

- name: Rename '{{ configFile }}' to conf
  ansible.builtin.copy:
    src: "~/.kube/{{ configFile }}"
    dest: "~/.kube/config"
    remote_src: yes
  connection: local
  delegate_to: localhost

- name: Remove file '{{ configFile }}' locally
  ansible.builtin.file:
    path: "~/.kube/{{ configFile }}"
    state: absent
  connection: local
  delegate_to: localhost

- name: Replace the Master node IP with the LB IP
  ansible.builtin.replace:
    path: "~/.kube/config"
    regexp: "server: https?://(.*):{{ kubernetes.controlPlanePort }}"
    replace: "server: https://{{ loadBalancerFacts.results[0].ansible_facts.facter_networking.ip }}:{{ kubernetes.controlPlanePort }}"
    mode: '0600'
    # this should be replaced with the virtual IP of LB(s) in future
  connection: local
  delegate_to: localhost
