---
# tasks file for roles/kubernetesCore role
- name: Create RBAC role for namespace '{{ rbac.role.metadata.namespace }}'
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: "{{ rbac.role.metadata.name }}"
        namespace: "{{ rbac.role.metadata.namespace }}"
      rules:
      - apiGroups: ["", "extensions", "apps", "kubeless.io", "networking.k8s.io"]
        resources: ["*"]
        verbs: ["*"]
      - apiGroups: ["batch"]
        resources:
        - jobs
        - cronjobs
        - functions
        verbs: ["*"]
  connection: local
  delegate_to: localhost
