---
# tasks file for roles/kubernetesCore roleBinding
- name: Create Role Bind for namespace '{{ rbac.roleBinding.metadata.namespace }}'
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: "{{ rbac.roleBinding.metadata.name }}"
        namespace: "{{ rbac.roleBinding.metadata.namespace }}"
      roleRef:
        kind: "{{ rbac.roleBinding.roleRef.kind }}"
        name: "{{ rbac.roleBinding.roleRef.name }}"
        apiGroup: rbac.authorization.k8s.io
      subjects:
      - kind: "{{ rbac.roleBinding.subjects.kind }}"
        name: "{{ rbac.roleBinding.subjects.name }}"
        namespace: "{{ rbac.roleBinding.subjects.namespace }}"
  connection: local
  delegate_to: localhost
