---
# tasks file for roles/kubernetesCore serviceAccount
- name: Create ServiceAccount in Namespace '{{ rbac.serviceAccount.metadata.namespace }}'
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ rbac.serviceAccount.metadata.name }}"
        namespace: "{{ rbac.serviceAccount.metadata.namespace }}"
  connection: local
  delegate_to: localhost
