---
# tasks file for containersCore createDirs
- name: Create dirs and recursively change ownership
  become: true
  ansible.builtin.file:
    recurse: yes
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ directories }}"
