---
- name: Change file ownership, group and permissions
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    recurse: yes
  loop: "{{ directoriesOwnedByOldUser }}"
