---
# handlers file for roles/consulClient
- name: restart consul
  become: true
  ansible.builtin.systemd:
    masked: no
    enabled: yes
    name: consul
    state: restarted
    daemon_reload: yes
