local:
  hosts:
    localhost:

demo:
  hosts:
    localhost:

sampleWithParameters:
  hosts:
    loaclhost:
  vars:
    uid: 9999
    gid: 9999
    user: 'myTechnicalUser'
    group: 'myTechnicalGroup'

kubernetesLoadBalancer:
  hosts:
    host1:
    host2:

kubernetes:
  hosts:
    host3:
    host4:
    host5:
  vars:
    overcommit_memory: false

kubernetesMasterNodes:
  hosts:
    hostMaster1: # prime (modify if change prime)
    hostMaster2: # secondary
    hostMaster3: # third

kubernetesIngressNodes:
  hosts:
    hostIngress1:
    hostIngress2:

prometheusClients:
  hosts:
    hostClient:
