---
# tasks file for roles/docker main
- name: populate service facts
  ansible.builtin.service_facts:
  no_log: true

- name: Stop and clean all containers / images
  ansible.builtin.include_tasks: container.yml

- name: Check deprecated docker package / directories
  ansible.builtin.include_tasks: docker.yml

- name: Check deprecated docker configurations
  ansible.builtin.include_tasks: daemon.yml
